daemon off;

events {
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet_stream;

    server {
        listen 3001;

        root /frontend/dist;
        index index.html index.html;

        location / {
            try_files $uri $uri/ /index.html;
        }
    }
}