services:
  backend:
    build: ./backend
    restart: unless-stopped
    networks:
      docker-network:
        # 10.69.42.201 will be assigned to frontend
        ipv4_address: 10.69.42.202
  proxy:
    build: ./proxy
    ports:
    - 80:80
    depends_on:
    - backend
    restart: unless-stopped
    networks:
      docker-network:
        ipv4_address: 10.69.42.210
networks:
  docker-network:
    ipam:
      config:
      - subnet: 10.69.42.0/24
