services:
  backend:
    build: ./backend
    restart: unless-stopped
    volumes:
      - ./logs/backend:/var/log/backend
  proxy:
    build: ./proxy
    ports:
      - 80:80
    depends_on:
      - backend
    restart: unless-stopped
    volumes:
      - ./logs/proxy:/var/log/nginx