services:
  backend:
    build: ./backend
    depends_on:
    - db
    restart: unless-stopped
    volumes:
    - ./logs/backend:/var/log/backend
  proxy:
    build: ./proxy
    ports:
    - 80:80
    depends_on:
    - backend
    restart: unless-stopped
    volumes:
    - ./logs/proxy:/var/log/nginx
  db:
    image: postgres:latest
    env_file:
    - ./.env
    restart: unless-stopped
    volumes:
    - ./db-data:/var/lib/postgresql