FROM python:3.13-alpine

WORKDIR /backend
COPY . .

# Temporary port until we set up a proxy
EXPOSE 3000

RUN pip install -r ./spec/req-prod.txt
ENTRYPOINT [ "gunicorn", "-b", "0.0.0.0:3000", "src.main:app" ]